gems:
  - jekyll-sitemap
  - jekyll-redirect-from
#  - algoliasearch-jekyll

staticurl: https://plot.ly/gh-pages/documentation/static/

exclude:
  - .sass-cache
  - scss
  - node_modules
  - gulpfile.js

#
#algolia:
#  application_id:      'UFNFY0UTNN'
#  index_name:          'help.plot.ly'
#  search_only_api_key: '58a3e4e581f186e87bd219d92431cc42'
